package org.shayvin.tourplanner.event;

public enum Event {
    ADD_TOUR,
    REMOVE_TOUR,
    EDIT_TOUR,
    SAVE_EDITED_TOUR,

    LIST_UPDATED,

    ENABLE_ADD_BUTTON,
    DISABLE_ADD_BUTTON,

    DISABLE_REMOVE_BUTTON,

    DISABLE_EDIT_BUTTON,

    TOUR_NAME_ADDED,
    TOUR_DESCRIPTION_ADDED,
    TOUR_START_ADDED,
    TOUR_DESTINATION_ADDED,
    TOUR_TYPE_ADDED,
    TOUR_DISTANCE_ADDED,
    TOUR_TIME_ADDED,
    TOUR_INFORMATION_ADDED,

    TOUR_SELECTED,
    TOUR_UNSELECTED,
    TOUR_UPDATED,

    ADD_TOUR_LOG,
    DELETE_TOUR_LOG,
    SELECT_TOUR_LOG,
    DELETE_TOUR_LOG_BUTTON_VISIBILITY,
}
